### PR TITLE
Replaced the Incident Response with a new updated version

### PR DESCRIPTION
**Pull request by P-rple**
## Overview of Changes

General overview of what has been changed
```
Modified IPTables documentation to removed errors, typos and add missing content. The added content is as follows: Docker Integration, Debugging Guidelines, and Useful commands.
```

## Reason for Modification

This section will list the reasons modification were preformed. This justifies why the changes are necessary or the documentation should be added.

## Verification

- [x] The documentation is completed, or does not contain work-in-progress/partially-completed sections.
- [x] The documentation is written in *Markdown* (Exception for Inject and Incident Reports).
- [x] Any Images are contained in a subdirectory `Images`.
- [x] Any scripts, Ansible Playbooks, Terraform scripts, etc. Have documentation explaining their purpose and use case.
- [x] Any scripts are tested.
- [x] I have assigned and notified a reviewer.

### CODE REVIEW

**Review by DaintyJet — DISMISSED** [review]
LGTM

**Comment by Zinkelburger** [comment]
Maybe we could reconsider the "fill in the form" style, and just try to note the issues in the executive summary. (we could also reconsider the inject template as well)
Also do we need the fake email at the top, where we will likely just repeat the executive summary?

We could simply have an executive summary, and then have sections expanding on each point. Like
```
# Executive Summary
I'm gonna talk about things 1, 2, 3.

# Thing 1
We did some stuff and here are some screenshots. We're the best.
Screenshot 1
<caption>

# Thing 2
We failed but here's our work. La la la
Screenshot 2
<caption>

# Thing 3
We did this thing
Screenshot 3
<caption>
explanation
```

**Comment by DaintyJet** [comment]
> Maybe we could reconsider the "fill in the form" style, and just try to note the issues in the executive summary. (we could also reconsider the inject template as well) Also do we need the fake email at the top, where we will likely just repeat the executive summary?
> 
> We could simply have an executive summary, and then have sections expanding on each point. Like
> 
> ```
> # Executive Summary
> I'm gonna talk about things 1, 2, 3.
> 
> # Thing 1
> We did some stuff and here are some screenshots. We're the best.
> Screenshot 1
> <caption>
> 
> # Thing 2
> We failed but here's our work. La la la
> Screenshot 2
> <caption>
> 
> # Thing 3
> We did this thing
> Screenshot 3
> <caption>
> explanation
> ```

We should remove the fake email. I would also say this line of thought is something to consider. But assuming we are writing this for a business (which I have no experience), it may be good to have the quick fill-in form style areas (maybe not boxes as we have discussed they lead to formatting issues) as this allows someone to quickly see the state of things without having to dig it out of the executive summery,

**Comment by DaintyJet** [comment]
Outdate branch

**Pull request closed without merging**
